### ISSUE TITLE
Containerize the application and make it deployable on k8s

### ISSUE THREAD

**Issue by satyamsi** [meganabyte/github#6]
- [x] Create Docker Container 
- [x] Run container with docker run xyz:latest 
- [x] Read up on K8s cluster 
- [x] Install k8s on local system using docker engine
- [x] Use helm to create charts and to deploy/configure the app

- [x] Read up on terraform 
- [x] Deploy K8s cluster in AWS (Get help from Guy to use his work)

**Comment by meganabyte** [comment]
Dockerized & ran app within container, created a helm chart to deployed app, used terraform to deploy kubernetes cluster & spin up eks cluster
